--------------------------------------------------------
--  File created - ×åòâúðòúê-Þëè-16-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SUPERMARKETS"."CATEGORIES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"SUBCATEGORYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEASURES
--------------------------------------------------------

  CREATE TABLE "SUPERMARKETS"."MEASURES" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "SUPERMARKETS"."PRODUCTS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(19,4), 
	"VENDORID" NUMBER(*,0), 
	"MEASUREID" NUMBER(*,0), 
	"CATEGORYID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENDORS
--------------------------------------------------------

  CREATE TABLE "SUPERMARKETS"."VENDORS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SUPERMARKETS.CATEGORIES
SET DEFINE OFF;
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Alcohol',null);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Beer',1);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Juice',null);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Soft Drink',null);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Food',null);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Chocolate',5);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Ice Scream',5);
Insert into SUPERMARKETS.CATEGORIES (NAME,PARENT_CATEGORY_ID) values ('Snacks',5);
REM INSERTING into SUPERMARKETS.MEASURES
SET DEFINE OFF;
Insert into SUPERMARKETS.MEASURES (NAME) values ('kg.');
Insert into SUPERMARKETS.MEASURES (NAME) values ('liters');
Insert into SUPERMARKETS.MEASURES (NAME) values ('pieces');
REM INSERTING into SUPERMARKETS.PRODUCTS
SET DEFINE OFF;
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Fanta',0.9,5,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Coca Cola',1.1,5,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Pepsi Cola',1,4,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Schweppes',0.9,6,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Canada Dry',2.5,6,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Hawaiian Punch',5.2,6,2,1);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Nestle Chocolate',1.34,1,1,6);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Chio Chips',1.25,8,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Sprite',0.95,5,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Mirinda',0.86,4,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Sevenup',1.12,4,2,4);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Almus Special',1.54,7,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Gredberg',1.23,7,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Almus Lager',1.34,7,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Almus Dark',1.23,7,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Lay Chips',1.45,9,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Doritos',2.11,9,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Ruffles',1.98,9,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Fritos',1.98,9,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Chio Tortillas',1.77,8,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Chio Taccos',1.23,8,1,8);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Vodka “Targovishte”',7.23,3,2,1);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Beer “Zagorka”',1.56,2,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Beer “Beck’s”',2.14,2,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Chocolate Milka',1.34,1,1,6);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Toffiffee',2.12,10,3,5);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Merci (candy)',2.12,10,3,5);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Nestle "Taraleji"',2.11,1,3,5);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Shugar "Sladea"',0.76,11,1,5);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Chaika',0.54,11,1,6);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Carling Black Label',3.67,12,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Carling Cider',2.67,12,2,1);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Carling Black Label Big',1.54,12,2,1);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Somersby cider',2.56,13,2,1);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Tuborg',3.45,13,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Grimbergen craft beers',2.89,13,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('Pirinsko',1.54,13,2,2);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values (' KITKAT',1.54,1,1,6);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('NESTLE LZ',1.23,1,1,6);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('NESTLE  GOLD FLAKES',2.45,1,1,5);
Insert into SUPERMARKETS.PRODUCTS (NAME,PRICE,VENDOR_ID,MEASURE_ID,CATEGORY_ID) values ('NESTLE CORN FLAKES',3.73,1,1,5);
REM INSERTING into SUPERMARKETS.VENDORS
SET DEFINE OFF;
Insert into SUPERMARKETS.VENDORS (NAME) values ('Nestle Sofia Corp.');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Zagorka Corp.');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Targovishte Bottling Company Ltd.');
Insert into SUPERMARKETS.VENDORS (NAME) values ('PepsiCo');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Coca Cola');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Dr Pepper Snapple Group');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Lomsko Pivo AD');
Insert into SUPERMARKETS.VENDORS (NAME) values (,'August Storck KG');
Insert into SUPERMARKETS.VENDORS (NAME) values ('CHIO-CHIPS KNABBERARTIKEL GMBH');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Frito-Lay Inc');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Zaharni Zavodi AD');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Molson Coors Brewing Company');
Insert into SUPERMARKETS.VENDORS (NAME) values ('Carlsberg Group');
--------------------------------------------------------
--  Constraints for Table MEASURES
--------------------------------------------------------

  ALTER TABLE "SUPERMARKETS"."MEASURES" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPERMARKETS"."MEASURES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPERMARKETS"."MEASURES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."MEASURES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SUPERMARKETS"."PRODUCTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" MODIFY ("CATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" MODIFY ("MEASUREID" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" MODIFY ("VENDORID" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "SUPERMARKETS"."CATEGORIES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPERMARKETS"."CATEGORIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."CATEGORIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENDORS
--------------------------------------------------------

  ALTER TABLE "SUPERMARKETS"."VENDORS" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPERMARKETS"."VENDORS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SUPERMARKETS"."VENDORS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SUPERMARKETS"."VENDORS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "SUPERMARKETS"."CATEGORIES" ADD CONSTRAINT "FK_CHILD" FOREIGN KEY ("SUBCATEGORYID")
	  REFERENCES "SUPERMARKETS"."CATEGORIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "SUPERMARKETS"."PRODUCTS" ADD CONSTRAINT "FK_CATEGORIES" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "SUPERMARKETS"."CATEGORIES" ("ID") ENABLE;
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" ADD CONSTRAINT "FK_MEASURES" FOREIGN KEY ("MEASUREID")
	  REFERENCES "SUPERMARKETS"."MEASURES" ("ID") ENABLE;
  ALTER TABLE "SUPERMARKETS"."PRODUCTS" ADD CONSTRAINT "FK_VENDORS" FOREIGN KEY ("VENDORID")
	  REFERENCES "SUPERMARKETS"."VENDORS" ("ID") ENABLE;
